server:
  port: 7070

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: contestowner-service
        uri: lb://contestowner-service
        predicates:
        - Path= /api/contest/**,/api/schedule/**
        
      - id: user-service
        uri: lb://user-service
        predicates:
        - Path= /api/user/**
         
      - id: teammanagement-service
        uri: lb://teammanagement-service
        predicates:
        - Path= /api/team/**
        
      - id: scoreboard-service
        uri: lb://scoreboard-service
        predicates:
        - Path= /api/scoreboard/matchscore/**
        
      