server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://${DB_URL:10.5.113.99}:${DB_PORT:3306}/${DB_NAME:sportmanagementsystem}
        databaseName:
        serverName:
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:root}
        connectionTimeout: 10000
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false